### ISSUE TITLE
Funguje to? :D

### ISSUE THREAD

**Issue by GamakCZ** [PMCoreX/CoreX#4]

**Comment by PikyCZ** [comment]
mělo ale nemám to zkompilovaná a navíc ted delam navic na AI a ještě na 0.16.. 
Pokud mas nejaky napad na zlepseni ci nejakou pripominku napis

**Comment by GamakCZ** [comment]
Kde vemu platnou .phar?

**Comment by PikyCZ** [comment]
Ted bych nedoporucoval dělat phar .. Dělám na AI a updatu na 0.16

**Comment by PikyCZ** [comment]
Přečti si Readme !!

**Comment by PikyCZ** [comment]
Přečti si Readme až udělám phar  dozvíš se to jako první .. :)
